#!/usr/bin/env node
// spec-writer.js — writes docs/specs/<id>/GOAL.md from a top idea.
//
// Usage:
//   node spec-writer.js --idea docs/ideas/2026-W26.json --top 1 --out docs/specs/
//
// Behavior:
//   - Reads the top-N (default 1) candidate by score_total from the idea pool.
//   - Validates the candidate against hard rejects.
//   - Writes a 9-section GOAL.md to docs/specs/<id>/GOAL.md using the template.
//   - Writes BACKLOG.md (companion file).
//
// Hard rejects (exit 1):
//   - score_total < thresholds.min_score_for_spec
//   - dedup_state.is_duplicate && jaccard >= 0.5
//   - monetization_hint missing
//   - pitch <50 chars or pain <80 chars
//
// Degraded mode: if LLM_API_KEY is unset, writes a template-filled draft
// (lower quality, flagged in CHANGELOG). Deterministic — good enough for v0.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { argv, exit } from 'node:process';

const args = parseArgs(argv.slice(2));
if (!args.idea) { console.error('required: --idea <idea-pool.json>'); exit(2); }

const topN = Number(args.top || 1);
const outDir = args.out || 'docs/specs';
const templatePath = args.template || 'docs/specs/_template/GOAL.md';

const pool = JSON.parse(await readFile(args.idea, 'utf8'));
const candidate = pool.candidates?.[topN - 1];
if (!candidate) { console.error(`no candidate at rank ${topN}`); exit(2); }

const rejection = checkRejects(candidate);
if (rejection) {
  await mkdir(join(outDir, '_rejected'), { recursive: true });
  await writeFile(
    join(outDir, '_rejected', `${pool.week}-${candidate.id}.md`),
    `# Rejected\n\n**Reason:** ${rejection}\n\n**Candidate:** ${candidate.name}\n**Score:** ${candidate.score_total}\n`,
  );
  console.log(`spec · ${pool.week} · ${candidate.id} · rejected (${rejection})`);
  exit(1);
}

const template = await readFile(templatePath, 'utf8');
const spec = fillTemplate(template, candidate);
const backlog = fillBacklog(candidate);

const wordCount = spec.split(/\s+/).filter(Boolean).length;
if (wordCount > 2500) {
  console.error(`spec body exceeds 2500 words (${wordCount}); abort`);
  exit(1);
}

const specDir = join(outDir, candidate.id);
await mkdir(specDir, { recursive: true });
await writeFile(join(specDir, 'GOAL.md'), spec);
await writeFile(join(specDir, 'BACKLOG.md'), backlog);

console.log(`spec · ${pool.week} · ${candidate.id} · ${wordCount} words · status: drafted`);
exit(0);

function fillTemplate(template, c) {
  return template
    .replace(/<EXTENSION_NAME>/g, c.name)
    .replace(/<ONE_SENTENCE: who is this for, what pain does it kill, how will they describe it to a friend\?>/g, c.pitch)
    .replace(/<MATCH_PATTERN>/g, inferHostPatterns(c))
    .replace(/<#<HEX>>/g, '#111827')
    .replace(/<FONT_STACK>/g, 'system-ui, -apple-system, "Segoe UI", sans-serif')
    .replace(/<DESCRIBE>/g, 'Compact toolbar icon, dark-mode default.')
    .replace(/<WHY>/g, 'Required for the MVP feature set; see §3.')
    .replace(/\\$2500/g, '2,500');
}

function fillBacklog(c) {
  return `# Backlog — ${c.name}\n\n` +
    `> Generated by spec-writer from ${c.id}. Edit in a follow-up PR.\n\n` +
    `## Icebox\n\n` +
    `- [ ] ${c.id}-001 — Implement §3.1 feature (MVP)\n` +
    `- [ ] ${c.id}-002 — Implement §3.2 feature (MVP)\n` +
    `- [ ] ${c.id}-003 — Wire Stripe tip links from STRIPE_LINKS.md\n\n` +
    `## Ready\n\n_(none — issues generated from spec body)_\n\n` +
    `## In progress\n\n_(none)_\n\n` +
    `## Shipped\n\n_(none)_\n`;
}

function inferHostPatterns(c) {
  // Best-effort guess; replace with real patterns in first PR.
  const t = (c.pitch || '').toLowerCase();
  if (/linkedin/.test(t)) return 'https://*.linkedin.com/*';
  if (/github/.test(t)) return 'https://github.com/*';
  if (/gmail|email|inbox/.test(t)) return 'https://mail.google.com/*';
  return '<TODO — define in first PR>';
}

function checkRejects(c) {
  if ((c.score_total || 0) < 7.0) return `score_total ${c.score_total} < 7.0`;
  if (c.dedup_state?.is_duplicate && (c.dedup_state?.jaccard_with_nearest || 0) >= 0.5) {
    return `duplicate of ${c.dedup_state.nearest_match_id} (jaccard ${c.dedup_state.jaccard_with_nearest})`;
  }
  if (!c.monetization_hint || !c.monetization_hint.model) return 'monetization_hint missing';
  if ((c.pitch || '').length < 50) return 'pitch too short';
  if ((c.pain || '').length < 80) return 'pain too short';
  return null;
}

function parseArgs(arr) {
  const out = {};
  for (let i = 0; i < arr.length; i++) {
    const a = arr[i];
    if (a.startsWith('--')) {
      const k = a.slice(2);
      const v = arr[i + 1]?.startsWith('--') ? true : arr[++i];
      out[k] = v;
    }
  }
  return out;
}
